name: Delete Old Releases

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    # Führe den Workflow einmal Wöchentlich aus
    - cron: '0 0 * * 0'

jobs:
  maintenance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get All Releases
        id: all_releases
        run: |
          all_releases=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -X GET "https://api.github.com/repos/${{ github.repository }}/releases" \
              | jq -r '.[] | .id')
          # Sortiere die Release-IDs in umgekehrter Reihenfolge
          sorted_releases=($(printf '%s\n' "${all_releases[@]}" | sort -nr))

          # Entferne die letzten fünf Release-IDs aus dem Array
          num_to_keep=5
          for ((i=0; i<${num_to_keep}; i++)); do
              unset 'sorted_releases[${i}]'
          done

          # Speichere die zu löschenden Release-IDs in eine Datei
          printf '%s\n' "${sorted_releases[@]}" > releases_to_delete.txt

      - name: Delete Old Releases
        id: delete_old_releases
        run: |
          while read -r release_id; do
            curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -X DELETE "https://api.github.com/repos/${{ github.repository }}/releases/$release_id"
            echo "Release $release_id gelöscht"
          done < releases_to_delete.txt
      
      - name: Get All Workflows
        id: all_workflows
        run: |
          all_workflows=$(ls -t .github/workflows | tail -n +6)
          printf '%s\n' "${all_workflows[@]}" > old_workflows.txt

      - name: Delete Old Workflows
        id: delete_old_workflows
        run: |
          while read -r workflow; do
            rm .github/workflows/"$workflow"
            echo "Workflow $workflow gelöscht"
          done < old_workflows.txt

      - name: Get All Files
        id: all_files
        run: |
          all_files=$(find . -type f | tail -n +6)
          printf '%s\n' "${all_files[@]}" > old_files.txt

      - name: Delete Old Files
        id: delete_old_files
        run: |
          while read -r file; do
            rm "$file"
            echo "Datei $file gelöscht"
          done < old_files.txt
